if(typeof DEPARTMENTCODE == undefined){
    var DEPARTMENTCODE = {};
    DEPARTMENTCODE.ALL = 0;
    DEPARTMENTCODE.RD = 1;
    DEPARTMENTCODE.NETWORKS = 2;
    DEPARTMENTCODE.ART = 3;
}

if(typeof DEPARTMENTSTR == undefined){
    var DEPARTMENTSTR = {};
    DEPARTMENTSTR.ALL = "中心";
    DEPARTMENTSTR.RD = "研发部";
    DEPARTMENTSTR.NETWORKS = "网络部";
    DEPARTMENTSTR.ART = "美工部";
}

if(typeof POSITIONCODE == undefined){
    var POSITIONCODE = {};
    POSITIONCODE.STAFF = 0;
    POSITIONCODE.INSTURCTOR = 1;
    POSITIONCODE.DIRECTOR = 2;
    POSITIONCODE.HEAD = 3;
    POSITIONCODE.VICEHEAD = 4;
    POSITIONCODE.GROUP = 5;
}

if(typeof POSITIONSTR == undefined){
    var POSITIONSTR = {};
    POSITIONSTR.STAFF = "员工";
    POSITIONSTR.INSTURCTOR = "指导老师";
    POSITIONSTR.DIRECTOR = "总监";
    POSITIONSTR.HEAD = "部长";
    POSITIONSTR.VICEHEAD = "副部长";
    POSITIONSTR.GROUP = "组长";
}